In [1]:
import numpy as np

# Section 5. N차원 배열의 형태 변경

### 5-1. 배열의 형태 변경 1: reshape()

In [7]:
arr = np.arange(12)
print(arr, arr.ndim)

arr = arr.reshape((3, 4))
print(arr, arr.ndim)

arr = arr.reshape((2, 3, 2))
print(arr, arr.ndim)

arr = arr.reshape((2, 2, 1, 3))
print(arr, arr.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11] 1
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 2
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]] 3
[[[[ 0  1  2]]

  [[ 3  4  5]]]


 [[[ 6  7  8]]

  [[ 9 10 11]]]] 4


### 5-2. 배열의 형태 변경 2: resize(), ravel()

In [9]:
arr = np.arange(12)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [11]:
arr.resize(3, 4)
print(arr)

arr = arr.ravel()
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [17]:
arr = np.arange(1, 13)
print(arr)

arr = arr.reshape(3, -1) # -1에 해당하는 부분에 자동으로 계산되게 함. 예를 들어 (3, -1)이면 (3, 4)가 되듯.
print(arr)

arr = arr.reshape(3, 2, -1) # -1은 하나만 가능
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


### 5-3. 배열의 형태 변경 3: expand_dims(), squeeze()

In [22]:
# expand_dims()
arr = np.array([1, 2])
print(arr, arr.shape)
arr = np.expand_dims(arr, axis=1)
print(arr, arr.shape)

[1 2] (2,)
[[1]
 [2]] (2, 1)


In [25]:
# squeeze()
arr = np.array([[1, 2]])
print(arr, arr.shape, arr.ndim)
arr = np.squeeze(arr, axis=0)
print(arr, arr.shape, arr.ndim)

arr = np.array([[[1],
                 [2],
                 [3]]])
print(arr, arr.shape, arr.ndim)
arr = np.squeeze(arr, axis=0)
print(arr, arr.shape, arr.ndim)

[[1 2]] (1, 2) 2
[1 2] (2,) 1
[[[1]
  [2]
  [3]]] (1, 3, 1) 3
[[1]
 [2]
 [3]] (3, 1) 2


In [27]:
arr = np.array([[[1, 2, 3]]])
print(arr, arr.shape, arr.ndim)
arr = np.squeeze(arr, axis=0)
print(arr, arr.shape, arr.ndim)

[[[1 2 3]]] (1, 1, 3) 3
[[1 2 3]] (1, 3) 2


### 5-4. 전치행렬(Transpose Matrix)

In [29]:
arr = np.array([[1, 2],
                [3, 4]])
print(arr.T)

arr = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])
print(arr.T)

[[1 3]
 [2 4]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [32]:
arr = np.array([[1, 2],
                [3, 4],
                [5, 6]])
print(arr.T)

arr2 = np.full((3, 2), 2)

# 1.(3, 2) 2.(2, 3) 3.Error
print((arr.T).dot(arr2))

[[1 3 5]
 [2 4 6]]
[[18 18]
 [24 24]]
