In [1]:
import numpy as np

# Section 2. N차원 배열의 인덱싱

### 2-1. 배열의 index 접근하기

In [9]:
# 1차원 배열
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr = np.arange(10)
print(arr)

print(arr[3])
print(arr[1])
print(arr[-3])
print(arr[-10])

[0 1 2 3 4 5 6 7 8 9]
3
1
7
0


In [13]:
# 2차원 배열
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])
print(arr, arr.shape, arr.ndim)
print(arr[0, 3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] (3, 4) 2
4


In [18]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr[3:8])
print(arr[3:])
print(arr[:7])
print(arr[:-1])

[3 4 5 6 7]
[3 4 5 6 7 8 9]
[0 1 2 3 4 5 6]
[0 1 2 3 4 5 6 7 8]


In [21]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

print(arr[0, :])
print(arr[:, 1])

[1 2 3 4]
[ 2  6 10]


In [23]:
print(arr[:3, :])
print(arr[:2, 2:])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[3 4]
 [7 8]]


### 2-2. 배열의 Fancy 인덱싱

In [26]:
# 1차원 배열
arr = np.array([5, 10, 15, 20, 25, 30])
print(arr[[0, 2, 4]])

[ 5 15 25]


In [30]:
# 2차원 배열
arr = np.array([[5, 10, 15, 20],
                [25, 30, 35, 40],
                [45, 50, 55, 60]])
print(arr[[0, 2], 2:])
print(arr[1:, [2, 3]])

[[15 20]
 [55 60]]
[[35 40]
 [55 60]]


### 2 - 3. 배열의 Boolean 인덱싱

In [34]:
arr = np.array([1, 2, 3, 4])
print(arr[[True, False, True, True]])

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8]])
print(arr[[True, False], True])

[1 3 4]
[[1 2 3 4]]


In [37]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8]])
print(arr[arr > 3])
print(arr[arr <= 2])

[4 5 6 7 8]
[1 2]
