In [1]:
import numpy as np

# Section 4. N차원 배열 정렬

### 4-1. 1차원 배열의 정렬

In [3]:
arr = np.random.randint(10, size=10)
print(arr)

[8 3 7 4 7 3 6 2 4 2]


In [5]:
print(np.sort(arr))
print(np.sort(arr)[::-1])

[2 2 3 3 4 4 6 7 7 8]
[8 7 7 6 4 4 3 3 2 2]


In [9]:
arr = np.sort(arr)
print(arr)
arr.sort()
print(arr)

[2 2 3 3 4 4 6 7 7 8]
[2 2 3 3 4 4 6 7 7 8]


### 4-2. 2차원 배열의 정렬

In [11]:
arr = np.random.randint(15, size=(3, 4))
print(arr)

[[13  5 14 14]
 [ 5  0 14  7]
 [ 5  0 12  8]]


In [15]:
print(np.sort(arr, axis=None)) # axis = None으로 하면 1차원 배열로 변환시켜 오름차순 정렬시킴

[ 0  0  5  5  5  7  8 12 13 14 14 14]


In [17]:
# argsort()
print(np.sort(arr, axis=0))
print(np.argsort(arr, axis=0)) # 그 값의 index에 해당되는 부분을 정렬시킴.

[[ 5  0 12  7]
 [ 5  0 14  8]
 [13  5 14 14]]
[[1 1 2 1]
 [2 2 0 2]
 [0 0 1 0]]
