In [1]:
import numpy as np

# Section 6. N차원 배열의 병합

### 6-1. 배열에 원소 추가 및 삭제

In [8]:
# Python list
arr = [1, 2, 3, 4, 5, 6, 7, 8]
arr.insert(2, 50)
print(arr)

# 1차원 배열
arr = np.arange(1, 9)
arr = np.insert(arr, 2, 50)
print(arr)

[1, 2, 50, 3, 4, 5, 6, 7, 8]
[ 1  2 50  3  4  5  6  7  8]


In [13]:
# 2차원 배열
arr = np.arange(1, 13).reshape(3, 4)
arr = np.insert(arr, 2, 50)
print(arr)

[ 1  2 50  3  4  5  6  7  8  9 10 11 12]


In [16]:
# delete
arr = np.arange(1, 13).reshape(3, 4)
print(arr)

arr = np.delete(arr, 2)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 1  2  4  5  6  7  8  9 10 11 12]


### 6-4. 배열 간의 병합

In [19]:
# append()
arr1 = np.arange(1, 13).reshape(3, 4)
arr2 = np.arange(13, 25).reshape(3, 4)

print(arr1)
print(arr2, end="\n\n")

# axis = 0
arr3 = np.append(arr1, arr2, axis=0)
print(arr3, end="\n\n")

# axis = 1
arr3 = np.append(arr1, arr2, axis=1)
print(arr3, end="\n\n")

# axis가 없으면
arr3 = np.append(arr1, arr2)
print(arr3, end="\n\n")

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]

[[ 1  2  3  4 13 14 15 16]
 [ 5  6  7  8 17 18 19 20]
 [ 9 10 11 12 21 22 23 24]]

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]



In [21]:
# vstack(), hstack()
arr1 = np.arange(1, 7).reshape(2, 3)
arr2 = np.arange(7, 13).reshape(2, 3)

arr3 = np.vstack((arr1, arr2))
print(arr3)

arr4 = np.hstack((arr1, arr2))
print(arr4)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [23]:
# concatenate()
arr1 = np.arange(1, 7).reshape(2, 3)
arr2 = np.arange(7, 13).reshape(2, 3)

arr3 = np.concatenate([arr1, arr2], axis=0)
print(arr3)

arr4 = np.concatenate([arr1, arr2], axis=1)
print(arr4)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


### 6-3. 배열 분할

In [28]:
# 2차원 배열
arr = np.arange(1, 13).reshape(3, 4)
print(arr)

# vsplit() => axis=0
arr_vsplit = np.vsplit(arr, 3)
print(arr_vsplit)

# hsplit() => axis=1
arr_hsplit = np.hsplit(arr, 2)
print(arr_hsplit)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]])]
[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12]])]


In [29]:
# 3차원 배열
arr = np.random.randint(0, 10, (4, 6, 8))
print(arr)

[[[6 5 3 4 2 2 7 8]
  [2 5 9 7 2 5 5 2]
  [2 7 8 5 9 5 8 4]
  [1 6 1 1 6 2 5 3]
  [2 5 7 9 7 1 8 5]
  [2 2 3 5 4 2 7 5]]

 [[4 6 4 6 5 4 7 0]
  [9 0 8 6 9 9 6 9]
  [8 2 3 8 5 6 8 1]
  [7 7 8 2 3 7 7 0]
  [6 8 6 0 6 2 5 2]
  [3 9 0 7 1 3 7 8]]

 [[7 5 1 2 6 7 7 2]
  [7 9 1 0 7 9 5 9]
  [0 3 4 0 7 7 8 0]
  [7 8 7 8 5 7 9 9]
  [9 5 3 6 3 6 7 9]
  [6 5 6 1 2 5 6 2]]

 [[4 4 8 7 7 4 9 8]
  [6 8 9 4 3 3 4 1]
  [4 8 4 0 7 4 4 4]
  [9 4 4 8 3 2 0 9]
  [0 8 6 1 1 1 8 0]
  [8 6 5 5 8 4 6 1]]]


In [31]:
arr_vsplit = np.vsplit(arr, 2)
print(arr_vsplit)

[array([[[6, 5, 3, 4, 2, 2, 7, 8],
        [2, 5, 9, 7, 2, 5, 5, 2],
        [2, 7, 8, 5, 9, 5, 8, 4],
        [1, 6, 1, 1, 6, 2, 5, 3],
        [2, 5, 7, 9, 7, 1, 8, 5],
        [2, 2, 3, 5, 4, 2, 7, 5]],

       [[4, 6, 4, 6, 5, 4, 7, 0],
        [9, 0, 8, 6, 9, 9, 6, 9],
        [8, 2, 3, 8, 5, 6, 8, 1],
        [7, 7, 8, 2, 3, 7, 7, 0],
        [6, 8, 6, 0, 6, 2, 5, 2],
        [3, 9, 0, 7, 1, 3, 7, 8]]]), array([[[7, 5, 1, 2, 6, 7, 7, 2],
        [7, 9, 1, 0, 7, 9, 5, 9],
        [0, 3, 4, 0, 7, 7, 8, 0],
        [7, 8, 7, 8, 5, 7, 9, 9],
        [9, 5, 3, 6, 3, 6, 7, 9],
        [6, 5, 6, 1, 2, 5, 6, 2]],

       [[4, 4, 8, 7, 7, 4, 9, 8],
        [6, 8, 9, 4, 3, 3, 4, 1],
        [4, 8, 4, 0, 7, 4, 4, 4],
        [9, 4, 4, 8, 3, 2, 0, 9],
        [0, 8, 6, 1, 1, 1, 8, 0],
        [8, 6, 5, 5, 8, 4, 6, 1]]])]


In [32]:
arr_hsplit = np.hsplit(arr, 2)
print(arr_hsplit)

[array([[[6, 5, 3, 4, 2, 2, 7, 8],
        [2, 5, 9, 7, 2, 5, 5, 2],
        [2, 7, 8, 5, 9, 5, 8, 4]],

       [[4, 6, 4, 6, 5, 4, 7, 0],
        [9, 0, 8, 6, 9, 9, 6, 9],
        [8, 2, 3, 8, 5, 6, 8, 1]],

       [[7, 5, 1, 2, 6, 7, 7, 2],
        [7, 9, 1, 0, 7, 9, 5, 9],
        [0, 3, 4, 0, 7, 7, 8, 0]],

       [[4, 4, 8, 7, 7, 4, 9, 8],
        [6, 8, 9, 4, 3, 3, 4, 1],
        [4, 8, 4, 0, 7, 4, 4, 4]]]), array([[[1, 6, 1, 1, 6, 2, 5, 3],
        [2, 5, 7, 9, 7, 1, 8, 5],
        [2, 2, 3, 5, 4, 2, 7, 5]],

       [[7, 7, 8, 2, 3, 7, 7, 0],
        [6, 8, 6, 0, 6, 2, 5, 2],
        [3, 9, 0, 7, 1, 3, 7, 8]],

       [[7, 8, 7, 8, 5, 7, 9, 9],
        [9, 5, 3, 6, 3, 6, 7, 9],
        [6, 5, 6, 1, 2, 5, 6, 2]],

       [[9, 4, 4, 8, 3, 2, 0, 9],
        [0, 8, 6, 1, 1, 1, 8, 0],
        [8, 6, 5, 5, 8, 4, 6, 1]]])]
